kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true


steps:
  - name: clone
    commands:
      - git clone $DRONE_REPO_LINK /var/www/deployer/tmp/$DRONE_REPO_NAME-$DRONE_STAGE_STARTED
  - name: composer install
    commands:
      - cd /var/www/deployer/tmp/$DRONE_REPO_NAME-$DRONE_STAGE_STARTED
      - composer install
      - pwd
      - ls -la
  - name: move project
    commands:
      - mv /var/www/deployer/tmp/$DRONE_REPO_NAME-$DRONE_STAGE_STARTED /var/www/deployer/
      - rm /var/www/$DRONE_REPO_NAME
      - ln -sf /var/www/deployer/$DRONE_REPO_NAME-$DRONE_STAGE_STARTED /var/www/$DRONE_REPO_NAME
    when:
      status:
        - success
