kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: composer install
    commands:
      - composer install
      - pwd
      - ls -la
  - name: move project
    commands:
      - echo 'move to ' $DRONE_REPO_NAME
      - rm -fr /var/www/$DRONE_REPO_NAME
      - mkdir /var/www/$DRONE_REPO_NAME
      - mv ./* /var/www/$DRONE_REPO_NAME
