kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: composer install
    commands:
      - composer install
      - pwd
      - ls -l
  - name: move project
    commands:
      - echo 'move to ' + $DRONE_COMMIT
      - echo $DRONE_RUNNER_ENVFILE
